version: '3.3'
services:
  web:
    build:
      context: .
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:3000
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
  mysql:
    container_name: parking_slot-db
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password --disable-log-bin
    environment:
      MYSQL_DATABASE: 'parking-slot'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '45045:3306'
    expose:
      - '45045'
    volumes:
      - /var/docker/parking-slot/mysql:/var/lib/mysql
      - /var/docker/parking-slot/mysql-files:/var/lib/mysql-files
      - /var/docker/parking-slot/etc/mysql:/etc/mysql
