version: '3.3'
services:
  mysql:
    container_name: parking_slot-db
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password --disable-log-bin
    environment:
      MYSQL_DATABASE: 'parking-slot'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '45045:3306'
    expose:
      - '45045'
    volumes:
      - /var/docker/parking-slot/mysql:/var/lib/mysql
      - /var/docker/parking-slot/mysql-files:/var/lib/mysql-files
      - /var/docker/parking-slot/etc/mysql:/etc/mysql
    networks:
      - app-network

  phpmyadmin:
    container_name: parking_slot-phpmyadmin
    image: phpmyadmin/phpmyadmin:edge
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - '46046:80'
    expose:
      - '46046'
    networks:
      - app-network

  web:
    build:
      context: .
    container_name: parking_slot-web
    command: npm run start:prod
    env_file: ../.env.production
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '8080:3000'
    expose:
      - '8080'
    depends_on:
      - mysql
    networks:
      - app-network

      #Docker Networks
networks:
  app-network:
    driver: bridge
